from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
import json
import os

import requests

ALERTS_LOG = Path("reports/wave5/alerts-log.jsonl")


def _append_alert(row: dict) -> None:
    ALERTS_LOG.parent.mkdir(parents=True, exist_ok=True)
    with ALERTS_LOG.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row) + "\n")


def _send_webhook(url: str, payload: dict) -> dict:
    if not url:
        return {"ok": False, "reason": "missing url"}
    r = requests.post(url, json=payload, timeout=20)
    return {"ok": 200 <= r.status_code < 300, "status_code": r.status_code}


def _send_pagerduty(payload: dict) -> dict:
    key = os.getenv("WAVE5_PAGERDUTY_ROUTING_KEY", "")
    if not key:
        return {"ok": False, "reason": "missing WAVE5_PAGERDUTY_ROUTING_KEY"}
    body = {
        "routing_key": key,
        "event_action": "trigger",
        "payload": {
            "summary": payload.get("summary", "Wave5 alert"),
            "severity": payload.get("severity", "critical"),
            "source": payload.get("source", "testops-wave5"),
            "custom_details": payload,
        },
    }
    return _send_webhook("https://events.pagerduty.com/v2/enqueue", body)


def _send_opsgenie(payload: dict) -> dict:
    key = os.getenv("WAVE5_OPSGENIE_API_KEY", "")
    if not key:
        return {"ok": False, "reason": "missing WAVE5_OPSGENIE_API_KEY"}
    headers = {"Authorization": f"GenieKey {key}"}
    body = {
        "message": payload.get("summary", "Wave5 alert"),
        "description": payload.get("description", ""),
        "priority": "P1" if payload.get("severity") == "critical" else "P3",
        "details": payload,
    }
    r = requests.post("https://api.opsgenie.com/v2/alerts", headers=headers, json=body, timeout=20)
    return {"ok": 200 <= r.status_code < 300, "status_code": r.status_code}


def send_alert(channel: str, payload: dict) -> dict:
    ch = (channel or "webhook").lower()
    if ch == "pagerduty":
        delivery = _send_pagerduty(payload)
    elif ch == "opsgenie":
        delivery = _send_opsgenie(payload)
    else:
        url = payload.get("webhook_url") or os.getenv("WAVE5_ALERT_WEBHOOK_URL", "")
        delivery = _send_webhook(url, payload)

    out = {
        "ts": datetime.now(UTC).isoformat(),
        "channel": ch,
        "payload": payload,
        "delivery": delivery,
    }
    _append_alert(out)
    return {"ok": delivery.get("ok", False), **out}


def notify_gate_block(gate_result: dict) -> dict:
    severity = "critical" if gate_result.get("decision") == "BLOCK" else "warning"
    payload = {
        "summary": f"Promotion gate {gate_result.get('decision', 'UNKNOWN')}",
        "description": "Wave3.2 gate decision generated by TestOps",
        "severity": severity,
        "source": "wave3.2/promotion",
        "gate": gate_result,
    }
    return send_alert(os.getenv("WAVE5_ALERT_DEFAULT_CHANNEL", "webhook"), payload)


def notify_critical_failure(source: str, details: dict) -> dict:
    payload = {
        "summary": "Critical failure detected",
        "description": f"Source={source}",
        "severity": "critical",
        "source": source,
        "details": details,
    }
    return send_alert(os.getenv("WAVE5_ALERT_DEFAULT_CHANNEL", "webhook"), payload)
